### PR TITLE
Code Deduplication

### PR DESCRIPTION
**Pull request by hargup**

### CODE REVIEW

**Comment by hargup** [comment]
I'm not able to run the code on `wigi.equiad.wmflabs`. Nikola depends on `Pillow` and `pip install Pillow` fails with the error at https://dpaste.de/jaq5 and `conda install Pillow` fails with

```
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
.
Solving package specifications: ................
Package plan for installation in environment /home/hargup/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |                0         699 KB
    libpng-1.6.17              |                0         214 KB
    freetype-2.5.2             |                2         2.5 MB
    libtiff-4.0.2              |                1         930 KB
    pillow-3.0.0               |           py27_0         788 KB
    ------------------------------------------------------------
                                           Total:         5.1 MB

The following NEW packages will be INSTALLED:

    freetype: 2.5.2-2     
    jpeg:     8d-0        
    libpng:   1.6.17-0    
    libtiff:  4.0.2-1     
    pillow:   3.0.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/jpeg-8d-0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/linux-64/jpeg-8d-0.tar.bz2
```

Others also faced similar error
- https://github.com/conda/conda/issues/1646 
- https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/-GEJuhyUWYk/87iuiHoDqEkJ

**Comment by raivivek** [comment]
I think don't think this is complete yet. For example, there are no changes to `conf.py` file which calls all the plot functions. Would you like to finish it @hargup?

**Comment by hargup** [comment]
I redefined the plot function, have a look.

**Comment by raivivek** [comment]
@hargup This will need update after recent changes. Let's hold it until we finalize the urgent tasks on visualizations.

**Comment by hargup** [comment]
Superseded by #75

**Pull request closed without merging**
