### PR TITLE
Add short toc type navigation, add sec spacing

### PR DESCRIPTION
**Pull request by raivivek**
#96

Signed-off-by: Vivek Rai vivekraiiitkgp@gmail.com

### CODE REVIEW

**Comment by raivivek** [comment]
@notconfusing Checkout these changes for #96. Does this work?

**Comment by notconfusing** [comment]
@vivekiitkgp I have to see it first. Can you show me how it would look on github?

**Comment by raivivek** [comment]
I have. Please fetch and build the "usability" branch as mentioned in the
PR.

**Comment by raivivek** [comment]
@notconfusing

**Pull request merged**
