### PR TITLE
Gender by Birth chart fixes

### LINKED ISSUE #47: by date of birth charts
- chart should include "nonbinary" in chart
- switch top10  and bottom10  be sorted by female-ratio rather than by year

### PR DESCRIPTION
**Pull request by hargup**
fixes #47
- Include non binary in the chart
- Sort by female ratio by date of birth

### CODE REVIEW

**Comment by raivivek** [comment]
Did you check the HTML table output? Do they overlap?

**Comment by hargup** [comment]
Yeah they do overlap, let me fix it.

**Comment by hargup** [comment]
The plots overlap only when we visit the website in a wide screen mode, on narrow screen it looks just fine. Any ideas on how to fix it?

**Comment by raivivek** [comment]
You may have to mix appropriate grid classes provided by Bootstrap's

## grid 12 column layout. Have a look at their documentation.

Vivek Rai
https://vivekiitkgp.github.io

**Comment by hargup** [comment]
Now we are always stacking the "Top 10" and "Bottom 10" charts, check it out.

**Comment by raivivek** [comment]
I considered that but I did not prefer that solution. Vertical space is
valuable.

## 

Vivek Rai
https://vivekiitkgp.github.io

**Comment by hargup** [comment]
I'm merging this for now it fixes the pain points of https://github.com/hargup/WIGI-website/issues/47. We can find a better solution for vertical spacing later.

**Pull request merged**
